<?php
/**
 * CampaignTargeting
 *
 * PHP version 5
 *
 * @category Class
 * @package  AnketologClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Документация к Анкетолог API
 *
 * ### Библиотеки для работы с API  * **PHP** https://github.com/anketolog/AnketologClient-php  ### Библиотеки на других языках  Вы можете самостоятельно сгенерировать библиотеку, [на любом доступном языке](https://github.com/swagger-api/swagger-codegen#api-clients), воспользовавшись [swagger-codegen](http://swagger.io/swagger-codegen). Конфигурационный файл можно скачать по [этой ссылке](https://anketolog.loc/api/external/v2/anketolog.yaml).  ### Работа с API  Работа с API осуществляется при помощи отправки POST-запросов на адрес:  ``` https://apiv2.anketolog.loc/{resource} ```  Необходимые параметры передаются в теле запроса в виде JSON-строки:  ``` {     \"survey_id\": \"ID опроса\" } ```  Для авторизации необходимо передать заголовок **X-Anketolog-ApiKey** в запросе:  ``` X-Anketolog-ApiKey: API_KEY ```  Ключ доступа к API можно получить в [разделе настроек](https://anketolog.loc/user/account/apikey)   ### Пример запроса  ``` curl -X POST \\   --header 'X-Anketolog-ApiKey: API_KEY' \\   -d '{\"survey_id\": \"ID опроса\"}' \\   'https://apiv2.anketolog.loc/survey/manage/info' ```
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AnketologClient\Model;

use \ArrayAccess;

/**
 * CampaignTargeting Class Doc Comment
 *
 * @category    Class */
 // @description Целевая аудитория кампании
/** 
 * @package     AnketologClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignTargeting implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'CampaignTargeting';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'vozrast' => '\AnketologClient\Model\CampaignTargetingVozrast',
        'pol' => '\AnketologClient\Model\CampaignTargetingPol',
        'mesto_zhitelstva' => '\AnketologClient\Model\CampaignTargetingMestoZhitelstva',
        'obrazovanie' => '\AnketologClient\Model\CampaignTargetingObrazovanie',
        'zanyatost' => '\AnketologClient\Model\CampaignTargetingZanyatost',
        'semya_i_deti' => '\AnketologClient\Model\CampaignTargetingSemyaIDeti',
        'dohody_i_rashody' => '\AnketologClient\Model\CampaignTargetingDohodyIRashody',
        'zhilischnye_usloviya' => '\AnketologClient\Model\CampaignTargetingZhilischnyeUsloviya',
        'lichnyy_transport' => '\AnketologClient\Model\CampaignTargetingLichnyyTransport',
        'peredvizhenie_po_gorodu' => '\AnketologClient\Model\CampaignTargetingPeredvizheniePoGorodu',
        'aviaperelety' => '\AnketologClient\Model\CampaignTargetingAviaperelety',
        'poyezdkizhd' => '\AnketologClient\Model\CampaignTargetingPoyezdkizhd',
        'produkty_pitaniya_i_alkogol' => '\AnketologClient\Model\CampaignTargetingProduktyPitaniyaIAlkogol',
        'kurenie' => '\AnketologClient\Model\CampaignTargetingKurenie',
        'odezhda_obuv' => '\AnketologClient\Model\CampaignTargetingOdezhdaObuv',
        'elektronika' => '\AnketologClient\Model\CampaignTargetingElektronika',
        'mobilnyy_telefon' => '\AnketologClient\Model\CampaignTargetingMobilnyyTelefon',
        'internet' => '\AnketologClient\Model\CampaignTargetingInternet',
        'domashnie_zhivotnye' => '\AnketologClient\Model\CampaignTargetingDomashnieZhivotnye',
        'platnye_uslugi' => '\AnketologClient\Model\CampaignTargetingPlatnyeUslugi',
        'krasota' => '\AnketologClient\Model\CampaignTargetingKrasota',
        'zdorove' => '\AnketologClient\Model\CampaignTargetingZdorove',
        'kultura_i_dosug' => '\AnketologClient\Model\CampaignTargetingKulturaIDosug',
        'sport_i_aktivnyy_otdyh' => '\AnketologClient\Model\CampaignTargetingSportIAktivnyyOtdyh',
        'uvlecheniya_i_interesy' => '\AnketologClient\Model\CampaignTargetingUvlecheniyaIInteresy',
        'puteshestviya' => '\AnketologClient\Model\CampaignTargetingPuteshestviya',
        'religioznaya_prinadlezhnost' => '\AnketologClient\Model\CampaignTargetingReligioznayaPrinadlezhnost',
        'politicheskaya_prinadlezhnost' => '\AnketologClient\Model\CampaignTargetingPoliticheskayaPrinadlezhnost'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'vozrast' => 'vozrast',
        'pol' => 'pol',
        'mesto_zhitelstva' => 'mesto_zhitelstva',
        'obrazovanie' => 'obrazovanie',
        'zanyatost' => 'zanyatost',
        'semya_i_deti' => 'semya_i_deti',
        'dohody_i_rashody' => 'dohody_i_rashody',
        'zhilischnye_usloviya' => 'zhilischnye_usloviya',
        'lichnyy_transport' => 'lichnyy_transport',
        'peredvizhenie_po_gorodu' => 'peredvizhenie_po_gorodu',
        'aviaperelety' => 'aviaperelety',
        'poyezdkizhd' => 'poyezdkizhd',
        'produkty_pitaniya_i_alkogol' => 'produkty_pitaniya_i_alkogol',
        'kurenie' => 'kurenie',
        'odezhda_obuv' => 'odezhda_obuv',
        'elektronika' => 'elektronika',
        'mobilnyy_telefon' => 'mobilnyy_telefon',
        'internet' => 'internet',
        'domashnie_zhivotnye' => 'domashnie_zhivotnye',
        'platnye_uslugi' => 'platnye_uslugi',
        'krasota' => 'krasota',
        'zdorove' => 'zdorove',
        'kultura_i_dosug' => 'kultura_i_dosug',
        'sport_i_aktivnyy_otdyh' => 'sport_i_aktivnyy_otdyh',
        'uvlecheniya_i_interesy' => 'uvlecheniya_i_interesy',
        'puteshestviya' => 'puteshestviya',
        'religioznaya_prinadlezhnost' => 'religioznaya_prinadlezhnost',
        'politicheskaya_prinadlezhnost' => 'politicheskaya_prinadlezhnost'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'vozrast' => 'setVozrast',
        'pol' => 'setPol',
        'mesto_zhitelstva' => 'setMestoZhitelstva',
        'obrazovanie' => 'setObrazovanie',
        'zanyatost' => 'setZanyatost',
        'semya_i_deti' => 'setSemyaIDeti',
        'dohody_i_rashody' => 'setDohodyIRashody',
        'zhilischnye_usloviya' => 'setZhilischnyeUsloviya',
        'lichnyy_transport' => 'setLichnyyTransport',
        'peredvizhenie_po_gorodu' => 'setPeredvizheniePoGorodu',
        'aviaperelety' => 'setAviaperelety',
        'poyezdkizhd' => 'setPoyezdkizhd',
        'produkty_pitaniya_i_alkogol' => 'setProduktyPitaniyaIAlkogol',
        'kurenie' => 'setKurenie',
        'odezhda_obuv' => 'setOdezhdaObuv',
        'elektronika' => 'setElektronika',
        'mobilnyy_telefon' => 'setMobilnyyTelefon',
        'internet' => 'setInternet',
        'domashnie_zhivotnye' => 'setDomashnieZhivotnye',
        'platnye_uslugi' => 'setPlatnyeUslugi',
        'krasota' => 'setKrasota',
        'zdorove' => 'setZdorove',
        'kultura_i_dosug' => 'setKulturaIDosug',
        'sport_i_aktivnyy_otdyh' => 'setSportIAktivnyyOtdyh',
        'uvlecheniya_i_interesy' => 'setUvlecheniyaIInteresy',
        'puteshestviya' => 'setPuteshestviya',
        'religioznaya_prinadlezhnost' => 'setReligioznayaPrinadlezhnost',
        'politicheskaya_prinadlezhnost' => 'setPoliticheskayaPrinadlezhnost'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'vozrast' => 'getVozrast',
        'pol' => 'getPol',
        'mesto_zhitelstva' => 'getMestoZhitelstva',
        'obrazovanie' => 'getObrazovanie',
        'zanyatost' => 'getZanyatost',
        'semya_i_deti' => 'getSemyaIDeti',
        'dohody_i_rashody' => 'getDohodyIRashody',
        'zhilischnye_usloviya' => 'getZhilischnyeUsloviya',
        'lichnyy_transport' => 'getLichnyyTransport',
        'peredvizhenie_po_gorodu' => 'getPeredvizheniePoGorodu',
        'aviaperelety' => 'getAviaperelety',
        'poyezdkizhd' => 'getPoyezdkizhd',
        'produkty_pitaniya_i_alkogol' => 'getProduktyPitaniyaIAlkogol',
        'kurenie' => 'getKurenie',
        'odezhda_obuv' => 'getOdezhdaObuv',
        'elektronika' => 'getElektronika',
        'mobilnyy_telefon' => 'getMobilnyyTelefon',
        'internet' => 'getInternet',
        'domashnie_zhivotnye' => 'getDomashnieZhivotnye',
        'platnye_uslugi' => 'getPlatnyeUslugi',
        'krasota' => 'getKrasota',
        'zdorove' => 'getZdorove',
        'kultura_i_dosug' => 'getKulturaIDosug',
        'sport_i_aktivnyy_otdyh' => 'getSportIAktivnyyOtdyh',
        'uvlecheniya_i_interesy' => 'getUvlecheniyaIInteresy',
        'puteshestviya' => 'getPuteshestviya',
        'religioznaya_prinadlezhnost' => 'getReligioznayaPrinadlezhnost',
        'politicheskaya_prinadlezhnost' => 'getPoliticheskayaPrinadlezhnost'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['vozrast'] = isset($data['vozrast']) ? $data['vozrast'] : null;
        $this->container['pol'] = isset($data['pol']) ? $data['pol'] : null;
        $this->container['mesto_zhitelstva'] = isset($data['mesto_zhitelstva']) ? $data['mesto_zhitelstva'] : null;
        $this->container['obrazovanie'] = isset($data['obrazovanie']) ? $data['obrazovanie'] : null;
        $this->container['zanyatost'] = isset($data['zanyatost']) ? $data['zanyatost'] : null;
        $this->container['semya_i_deti'] = isset($data['semya_i_deti']) ? $data['semya_i_deti'] : null;
        $this->container['dohody_i_rashody'] = isset($data['dohody_i_rashody']) ? $data['dohody_i_rashody'] : null;
        $this->container['zhilischnye_usloviya'] = isset($data['zhilischnye_usloviya']) ? $data['zhilischnye_usloviya'] : null;
        $this->container['lichnyy_transport'] = isset($data['lichnyy_transport']) ? $data['lichnyy_transport'] : null;
        $this->container['peredvizhenie_po_gorodu'] = isset($data['peredvizhenie_po_gorodu']) ? $data['peredvizhenie_po_gorodu'] : null;
        $this->container['aviaperelety'] = isset($data['aviaperelety']) ? $data['aviaperelety'] : null;
        $this->container['poyezdkizhd'] = isset($data['poyezdkizhd']) ? $data['poyezdkizhd'] : null;
        $this->container['produkty_pitaniya_i_alkogol'] = isset($data['produkty_pitaniya_i_alkogol']) ? $data['produkty_pitaniya_i_alkogol'] : null;
        $this->container['kurenie'] = isset($data['kurenie']) ? $data['kurenie'] : null;
        $this->container['odezhda_obuv'] = isset($data['odezhda_obuv']) ? $data['odezhda_obuv'] : null;
        $this->container['elektronika'] = isset($data['elektronika']) ? $data['elektronika'] : null;
        $this->container['mobilnyy_telefon'] = isset($data['mobilnyy_telefon']) ? $data['mobilnyy_telefon'] : null;
        $this->container['internet'] = isset($data['internet']) ? $data['internet'] : null;
        $this->container['domashnie_zhivotnye'] = isset($data['domashnie_zhivotnye']) ? $data['domashnie_zhivotnye'] : null;
        $this->container['platnye_uslugi'] = isset($data['platnye_uslugi']) ? $data['platnye_uslugi'] : null;
        $this->container['krasota'] = isset($data['krasota']) ? $data['krasota'] : null;
        $this->container['zdorove'] = isset($data['zdorove']) ? $data['zdorove'] : null;
        $this->container['kultura_i_dosug'] = isset($data['kultura_i_dosug']) ? $data['kultura_i_dosug'] : null;
        $this->container['sport_i_aktivnyy_otdyh'] = isset($data['sport_i_aktivnyy_otdyh']) ? $data['sport_i_aktivnyy_otdyh'] : null;
        $this->container['uvlecheniya_i_interesy'] = isset($data['uvlecheniya_i_interesy']) ? $data['uvlecheniya_i_interesy'] : null;
        $this->container['puteshestviya'] = isset($data['puteshestviya']) ? $data['puteshestviya'] : null;
        $this->container['religioznaya_prinadlezhnost'] = isset($data['religioznaya_prinadlezhnost']) ? $data['religioznaya_prinadlezhnost'] : null;
        $this->container['politicheskaya_prinadlezhnost'] = isset($data['politicheskaya_prinadlezhnost']) ? $data['politicheskaya_prinadlezhnost'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets vozrast
     * @return \AnketologClient\Model\CampaignTargetingVozrast
     */
    public function getVozrast()
    {
        return $this->container['vozrast'];
    }

    /**
     * Sets vozrast
     * @param \AnketologClient\Model\CampaignTargetingVozrast $vozrast
     * @return $this
     */
    public function setVozrast($vozrast)
    {
        $this->container['vozrast'] = $vozrast;

        return $this;
    }

    /**
     * Gets pol
     * @return \AnketologClient\Model\CampaignTargetingPol
     */
    public function getPol()
    {
        return $this->container['pol'];
    }

    /**
     * Sets pol
     * @param \AnketologClient\Model\CampaignTargetingPol $pol
     * @return $this
     */
    public function setPol($pol)
    {
        $this->container['pol'] = $pol;

        return $this;
    }

    /**
     * Gets mesto_zhitelstva
     * @return \AnketologClient\Model\CampaignTargetingMestoZhitelstva
     */
    public function getMestoZhitelstva()
    {
        return $this->container['mesto_zhitelstva'];
    }

    /**
     * Sets mesto_zhitelstva
     * @param \AnketologClient\Model\CampaignTargetingMestoZhitelstva $mesto_zhitelstva
     * @return $this
     */
    public function setMestoZhitelstva($mesto_zhitelstva)
    {
        $this->container['mesto_zhitelstva'] = $mesto_zhitelstva;

        return $this;
    }

    /**
     * Gets obrazovanie
     * @return \AnketologClient\Model\CampaignTargetingObrazovanie
     */
    public function getObrazovanie()
    {
        return $this->container['obrazovanie'];
    }

    /**
     * Sets obrazovanie
     * @param \AnketologClient\Model\CampaignTargetingObrazovanie $obrazovanie
     * @return $this
     */
    public function setObrazovanie($obrazovanie)
    {
        $this->container['obrazovanie'] = $obrazovanie;

        return $this;
    }

    /**
     * Gets zanyatost
     * @return \AnketologClient\Model\CampaignTargetingZanyatost
     */
    public function getZanyatost()
    {
        return $this->container['zanyatost'];
    }

    /**
     * Sets zanyatost
     * @param \AnketologClient\Model\CampaignTargetingZanyatost $zanyatost
     * @return $this
     */
    public function setZanyatost($zanyatost)
    {
        $this->container['zanyatost'] = $zanyatost;

        return $this;
    }

    /**
     * Gets semya_i_deti
     * @return \AnketologClient\Model\CampaignTargetingSemyaIDeti
     */
    public function getSemyaIDeti()
    {
        return $this->container['semya_i_deti'];
    }

    /**
     * Sets semya_i_deti
     * @param \AnketologClient\Model\CampaignTargetingSemyaIDeti $semya_i_deti
     * @return $this
     */
    public function setSemyaIDeti($semya_i_deti)
    {
        $this->container['semya_i_deti'] = $semya_i_deti;

        return $this;
    }

    /**
     * Gets dohody_i_rashody
     * @return \AnketologClient\Model\CampaignTargetingDohodyIRashody
     */
    public function getDohodyIRashody()
    {
        return $this->container['dohody_i_rashody'];
    }

    /**
     * Sets dohody_i_rashody
     * @param \AnketologClient\Model\CampaignTargetingDohodyIRashody $dohody_i_rashody
     * @return $this
     */
    public function setDohodyIRashody($dohody_i_rashody)
    {
        $this->container['dohody_i_rashody'] = $dohody_i_rashody;

        return $this;
    }

    /**
     * Gets zhilischnye_usloviya
     * @return \AnketologClient\Model\CampaignTargetingZhilischnyeUsloviya
     */
    public function getZhilischnyeUsloviya()
    {
        return $this->container['zhilischnye_usloviya'];
    }

    /**
     * Sets zhilischnye_usloviya
     * @param \AnketologClient\Model\CampaignTargetingZhilischnyeUsloviya $zhilischnye_usloviya
     * @return $this
     */
    public function setZhilischnyeUsloviya($zhilischnye_usloviya)
    {
        $this->container['zhilischnye_usloviya'] = $zhilischnye_usloviya;

        return $this;
    }

    /**
     * Gets lichnyy_transport
     * @return \AnketologClient\Model\CampaignTargetingLichnyyTransport
     */
    public function getLichnyyTransport()
    {
        return $this->container['lichnyy_transport'];
    }

    /**
     * Sets lichnyy_transport
     * @param \AnketologClient\Model\CampaignTargetingLichnyyTransport $lichnyy_transport
     * @return $this
     */
    public function setLichnyyTransport($lichnyy_transport)
    {
        $this->container['lichnyy_transport'] = $lichnyy_transport;

        return $this;
    }

    /**
     * Gets peredvizhenie_po_gorodu
     * @return \AnketologClient\Model\CampaignTargetingPeredvizheniePoGorodu
     */
    public function getPeredvizheniePoGorodu()
    {
        return $this->container['peredvizhenie_po_gorodu'];
    }

    /**
     * Sets peredvizhenie_po_gorodu
     * @param \AnketologClient\Model\CampaignTargetingPeredvizheniePoGorodu $peredvizhenie_po_gorodu
     * @return $this
     */
    public function setPeredvizheniePoGorodu($peredvizhenie_po_gorodu)
    {
        $this->container['peredvizhenie_po_gorodu'] = $peredvizhenie_po_gorodu;

        return $this;
    }

    /**
     * Gets aviaperelety
     * @return \AnketologClient\Model\CampaignTargetingAviaperelety
     */
    public function getAviaperelety()
    {
        return $this->container['aviaperelety'];
    }

    /**
     * Sets aviaperelety
     * @param \AnketologClient\Model\CampaignTargetingAviaperelety $aviaperelety
     * @return $this
     */
    public function setAviaperelety($aviaperelety)
    {
        $this->container['aviaperelety'] = $aviaperelety;

        return $this;
    }

    /**
     * Gets poyezdkizhd
     * @return \AnketologClient\Model\CampaignTargetingPoyezdkizhd
     */
    public function getPoyezdkizhd()
    {
        return $this->container['poyezdkizhd'];
    }

    /**
     * Sets poyezdkizhd
     * @param \AnketologClient\Model\CampaignTargetingPoyezdkizhd $poyezdkizhd
     * @return $this
     */
    public function setPoyezdkizhd($poyezdkizhd)
    {
        $this->container['poyezdkizhd'] = $poyezdkizhd;

        return $this;
    }

    /**
     * Gets produkty_pitaniya_i_alkogol
     * @return \AnketologClient\Model\CampaignTargetingProduktyPitaniyaIAlkogol
     */
    public function getProduktyPitaniyaIAlkogol()
    {
        return $this->container['produkty_pitaniya_i_alkogol'];
    }

    /**
     * Sets produkty_pitaniya_i_alkogol
     * @param \AnketologClient\Model\CampaignTargetingProduktyPitaniyaIAlkogol $produkty_pitaniya_i_alkogol
     * @return $this
     */
    public function setProduktyPitaniyaIAlkogol($produkty_pitaniya_i_alkogol)
    {
        $this->container['produkty_pitaniya_i_alkogol'] = $produkty_pitaniya_i_alkogol;

        return $this;
    }

    /**
     * Gets kurenie
     * @return \AnketologClient\Model\CampaignTargetingKurenie
     */
    public function getKurenie()
    {
        return $this->container['kurenie'];
    }

    /**
     * Sets kurenie
     * @param \AnketologClient\Model\CampaignTargetingKurenie $kurenie
     * @return $this
     */
    public function setKurenie($kurenie)
    {
        $this->container['kurenie'] = $kurenie;

        return $this;
    }

    /**
     * Gets odezhda_obuv
     * @return \AnketologClient\Model\CampaignTargetingOdezhdaObuv
     */
    public function getOdezhdaObuv()
    {
        return $this->container['odezhda_obuv'];
    }

    /**
     * Sets odezhda_obuv
     * @param \AnketologClient\Model\CampaignTargetingOdezhdaObuv $odezhda_obuv
     * @return $this
     */
    public function setOdezhdaObuv($odezhda_obuv)
    {
        $this->container['odezhda_obuv'] = $odezhda_obuv;

        return $this;
    }

    /**
     * Gets elektronika
     * @return \AnketologClient\Model\CampaignTargetingElektronika
     */
    public function getElektronika()
    {
        return $this->container['elektronika'];
    }

    /**
     * Sets elektronika
     * @param \AnketologClient\Model\CampaignTargetingElektronika $elektronika
     * @return $this
     */
    public function setElektronika($elektronika)
    {
        $this->container['elektronika'] = $elektronika;

        return $this;
    }

    /**
     * Gets mobilnyy_telefon
     * @return \AnketologClient\Model\CampaignTargetingMobilnyyTelefon
     */
    public function getMobilnyyTelefon()
    {
        return $this->container['mobilnyy_telefon'];
    }

    /**
     * Sets mobilnyy_telefon
     * @param \AnketologClient\Model\CampaignTargetingMobilnyyTelefon $mobilnyy_telefon
     * @return $this
     */
    public function setMobilnyyTelefon($mobilnyy_telefon)
    {
        $this->container['mobilnyy_telefon'] = $mobilnyy_telefon;

        return $this;
    }

    /**
     * Gets internet
     * @return \AnketologClient\Model\CampaignTargetingInternet
     */
    public function getInternet()
    {
        return $this->container['internet'];
    }

    /**
     * Sets internet
     * @param \AnketologClient\Model\CampaignTargetingInternet $internet
     * @return $this
     */
    public function setInternet($internet)
    {
        $this->container['internet'] = $internet;

        return $this;
    }

    /**
     * Gets domashnie_zhivotnye
     * @return \AnketologClient\Model\CampaignTargetingDomashnieZhivotnye
     */
    public function getDomashnieZhivotnye()
    {
        return $this->container['domashnie_zhivotnye'];
    }

    /**
     * Sets domashnie_zhivotnye
     * @param \AnketologClient\Model\CampaignTargetingDomashnieZhivotnye $domashnie_zhivotnye
     * @return $this
     */
    public function setDomashnieZhivotnye($domashnie_zhivotnye)
    {
        $this->container['domashnie_zhivotnye'] = $domashnie_zhivotnye;

        return $this;
    }

    /**
     * Gets platnye_uslugi
     * @return \AnketologClient\Model\CampaignTargetingPlatnyeUslugi
     */
    public function getPlatnyeUslugi()
    {
        return $this->container['platnye_uslugi'];
    }

    /**
     * Sets platnye_uslugi
     * @param \AnketologClient\Model\CampaignTargetingPlatnyeUslugi $platnye_uslugi
     * @return $this
     */
    public function setPlatnyeUslugi($platnye_uslugi)
    {
        $this->container['platnye_uslugi'] = $platnye_uslugi;

        return $this;
    }

    /**
     * Gets krasota
     * @return \AnketologClient\Model\CampaignTargetingKrasota
     */
    public function getKrasota()
    {
        return $this->container['krasota'];
    }

    /**
     * Sets krasota
     * @param \AnketologClient\Model\CampaignTargetingKrasota $krasota
     * @return $this
     */
    public function setKrasota($krasota)
    {
        $this->container['krasota'] = $krasota;

        return $this;
    }

    /**
     * Gets zdorove
     * @return \AnketologClient\Model\CampaignTargetingZdorove
     */
    public function getZdorove()
    {
        return $this->container['zdorove'];
    }

    /**
     * Sets zdorove
     * @param \AnketologClient\Model\CampaignTargetingZdorove $zdorove
     * @return $this
     */
    public function setZdorove($zdorove)
    {
        $this->container['zdorove'] = $zdorove;

        return $this;
    }

    /**
     * Gets kultura_i_dosug
     * @return \AnketologClient\Model\CampaignTargetingKulturaIDosug
     */
    public function getKulturaIDosug()
    {
        return $this->container['kultura_i_dosug'];
    }

    /**
     * Sets kultura_i_dosug
     * @param \AnketologClient\Model\CampaignTargetingKulturaIDosug $kultura_i_dosug
     * @return $this
     */
    public function setKulturaIDosug($kultura_i_dosug)
    {
        $this->container['kultura_i_dosug'] = $kultura_i_dosug;

        return $this;
    }

    /**
     * Gets sport_i_aktivnyy_otdyh
     * @return \AnketologClient\Model\CampaignTargetingSportIAktivnyyOtdyh
     */
    public function getSportIAktivnyyOtdyh()
    {
        return $this->container['sport_i_aktivnyy_otdyh'];
    }

    /**
     * Sets sport_i_aktivnyy_otdyh
     * @param \AnketologClient\Model\CampaignTargetingSportIAktivnyyOtdyh $sport_i_aktivnyy_otdyh
     * @return $this
     */
    public function setSportIAktivnyyOtdyh($sport_i_aktivnyy_otdyh)
    {
        $this->container['sport_i_aktivnyy_otdyh'] = $sport_i_aktivnyy_otdyh;

        return $this;
    }

    /**
     * Gets uvlecheniya_i_interesy
     * @return \AnketologClient\Model\CampaignTargetingUvlecheniyaIInteresy
     */
    public function getUvlecheniyaIInteresy()
    {
        return $this->container['uvlecheniya_i_interesy'];
    }

    /**
     * Sets uvlecheniya_i_interesy
     * @param \AnketologClient\Model\CampaignTargetingUvlecheniyaIInteresy $uvlecheniya_i_interesy
     * @return $this
     */
    public function setUvlecheniyaIInteresy($uvlecheniya_i_interesy)
    {
        $this->container['uvlecheniya_i_interesy'] = $uvlecheniya_i_interesy;

        return $this;
    }

    /**
     * Gets puteshestviya
     * @return \AnketologClient\Model\CampaignTargetingPuteshestviya
     */
    public function getPuteshestviya()
    {
        return $this->container['puteshestviya'];
    }

    /**
     * Sets puteshestviya
     * @param \AnketologClient\Model\CampaignTargetingPuteshestviya $puteshestviya
     * @return $this
     */
    public function setPuteshestviya($puteshestviya)
    {
        $this->container['puteshestviya'] = $puteshestviya;

        return $this;
    }

    /**
     * Gets religioznaya_prinadlezhnost
     * @return \AnketologClient\Model\CampaignTargetingReligioznayaPrinadlezhnost
     */
    public function getReligioznayaPrinadlezhnost()
    {
        return $this->container['religioznaya_prinadlezhnost'];
    }

    /**
     * Sets religioznaya_prinadlezhnost
     * @param \AnketologClient\Model\CampaignTargetingReligioznayaPrinadlezhnost $religioznaya_prinadlezhnost
     * @return $this
     */
    public function setReligioznayaPrinadlezhnost($religioznaya_prinadlezhnost)
    {
        $this->container['religioznaya_prinadlezhnost'] = $religioznaya_prinadlezhnost;

        return $this;
    }

    /**
     * Gets politicheskaya_prinadlezhnost
     * @return \AnketologClient\Model\CampaignTargetingPoliticheskayaPrinadlezhnost
     */
    public function getPoliticheskayaPrinadlezhnost()
    {
        return $this->container['politicheskaya_prinadlezhnost'];
    }

    /**
     * Sets politicheskaya_prinadlezhnost
     * @param \AnketologClient\Model\CampaignTargetingPoliticheskayaPrinadlezhnost $politicheskaya_prinadlezhnost
     * @return $this
     */
    public function setPoliticheskayaPrinadlezhnost($politicheskaya_prinadlezhnost)
    {
        $this->container['politicheskaya_prinadlezhnost'] = $politicheskaya_prinadlezhnost;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\AnketologClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\AnketologClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}


