<?php
/**
 * SurveySurveyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AnketologClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Anketolog API v2.0
 *
 * ### Клиенты:  * [**PHP**](https://github.com/anketolog/AnketologClient-php)  ### Клиенты на других языках:  * Скачайте конфигурационный [swagger-файл](https://anketolog.ru/api/external/v2/docs/anketolog.yaml) * Воспользуйтесь официальным [генератором](http://swagger.io/swagger-codegen/)   ([список поддерживаемых языков](https://github.com/swagger-api/swagger-codegen#api-clients))
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AnketologClient;

/**
 * SurveySurveyTest Class Doc Comment
 *
 * @category    Class */
// * @description Опрос
/**
 * @package     AnketologClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SurveySurveyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SurveySurvey"
     */
    public function testSurveySurvey()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "create_date"
     */
    public function testPropertyCreateDate()
    {

    }

    /**
     * Test attribute "update_date"
     */
    public function testPropertyUpdateDate()
    {

    }

    /**
     * Test attribute "lock_date"
     */
    public function testPropertyLockDate()
    {

    }

    /**
     * Test attribute "archive_date"
     */
    public function testPropertyArchiveDate()
    {

    }

    /**
     * Test attribute "suspend_date"
     */
    public function testPropertySuspendDate()
    {

    }

    /**
     * Test attribute "is_suspended"
     */
    public function testPropertyIsSuspended()
    {

    }

    /**
     * Test attribute "is_locked"
     */
    public function testPropertyIsLocked()
    {

    }

    /**
     * Test attribute "is_archive"
     */
    public function testPropertyIsArchive()
    {

    }

    /**
     * Test attribute "revision_id"
     */
    public function testPropertyRevisionId()
    {

    }

    /**
     * Test attribute "personalpage"
     */
    public function testPropertyPersonalpage()
    {

    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {

    }

    /**
     * Test attribute "settings"
     */
    public function testPropertySettings()
    {

    }

}
