<?php
/**
 * PersonalpageApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Anketolog API 2.0
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PersonalpageApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PersonalpageApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for listsManageArchive
     *
     * .
     *
     */
    public function testListsManageArchive()
    {

    }

    /**
     * Test case for personalpageCollectorCreatealias
     *
     * .
     *
     */
    public function testPersonalpageCollectorCreatealias()
    {

    }

    /**
     * Test case for personalpageCollectorCreatewidget
     *
     * .
     *
     */
    public function testPersonalpageCollectorCreatewidget()
    {

    }

    /**
     * Test case for personalpageCollectorList
     *
     * .
     *
     */
    public function testPersonalpageCollectorList()
    {

    }

    /**
     * Test case for personalpageCollectorUpdatealias
     *
     * .
     *
     */
    public function testPersonalpageCollectorUpdatealias()
    {

    }

    /**
     * Test case for personalpageCollectorUpdatewidget
     *
     * .
     *
     */
    public function testPersonalpageCollectorUpdatewidget()
    {

    }

    /**
     * Test case for personalpageManageCreate
     *
     * .
     *
     */
    public function testPersonalpageManageCreate()
    {

    }

    /**
     * Test case for personalpageManageInfo
     *
     * .
     *
     */
    public function testPersonalpageManageInfo()
    {

    }

    /**
     * Test case for personalpageManageList
     *
     * .
     *
     */
    public function testPersonalpageManageList()
    {

    }

    /**
     * Test case for personalpageManageRestore
     *
     * .
     *
     */
    public function testPersonalpageManageRestore()
    {

    }

    /**
     * Test case for personalpageManageUpdate
     *
     * .
     *
     */
    public function testPersonalpageManageUpdate()
    {

    }

}
